// COPYRIGHT NOTICE (NOT TO BE REMOVED):
//
// This file, or parts of it, or modified versions of it, may not be copied,
// reproduced or transmitted in any form, including reprinting, translation,
// photocopying or microfilming, or by any means, electronic, mechanical or
// otherwise, or stored in a retrieval system, or used for any purpose, without
// the prior written permission of all Owners unless it is explicitly marked as
// having Classification `Public'.
//   Classification: Restricted.
//
// Owners of this file give notice:
//   (c) Copyright 2010-2011 PES Software Engineering for Embedded Systems, TU Berlin
//
// Authors:
//		Sabine Glesner
//		Robert Reicherdt
//		Elke Salecker
//		Volker Seeker
//		Joachim Kuhnert
// 		Roman Busse
//
// All rights, including copyrights, reserved.
//
// This file contains or may contain restricted information and is UNPUBLISHED
// PROPRIETARY SOURCE CODE OF THE Owners.  The Copyright Notice(s) above do not
// evidence any actual or intended publication of such source code.  This file
// is additionally subject to the conditions listed in the RESTRICTIONS file
// and is with NO WARRANTY.
//
// END OF COPYRIGHT NOTICE
//----------------------------------------------------
// The following code was generated by CUP v0.10k TUM Edition 20050516
// Tue Jun 21 10:53:18 CEST 2011
//----------------------------------------------------

package de.tu_berlin.pes.memo.parser.stateflow.stateflowparser;

/** CUP generated interface containing symbol constants. */
public interface StateflowStateScannerSymbol {
	/* terminals */
	public static final int PLUSPLUS = 10;
	public static final int STRING_LITERAL = 44;
	public static final int GTEQ = 23;
	public static final int MULT = 14;
	public static final int LTEQ = 22;
	public static final int XOR = 27;
	public static final int LPAREN = 7;
	public static final int MULTASS = 31;
	public static final int MINUS = 13;
	public static final int TILDE = 47;
	public static final int RPAREN = 8;
	public static final int BOOLEAN_LITERAL = 43;
	public static final int OROR = 30;
	public static final int SEMICOLON = 45;
	public static final int NOT = 15;
	public static final int AND = 26;
	public static final int LT = 20;
	public static final int OR = 28;
	public static final int COMMA = 6;
	public static final int ON = 51;
	public static final int DIV = 16;
	public static final int ANDAND = 29;
	public static final int EXIT = 50;
	public static final int PLUS = 12;
	public static final int DOT = 5;
	public static final int ID = 4;
	public static final int BIND = 52;
	public static final int EOF = 0;
	public static final int MINUSMINUS = 11;
	public static final int ASS = 36;
	public static final int error = 1;
	public static final int ORASS = 39;
	public static final int MODASS = 33;
	public static final int EQEQ = 24;
	public static final int MOD = 17;
	public static final int ANDASS = 37;
	public static final int LBRACK = 2;
	public static final int ARROW = 40;
	public static final int COLON = 9;
	public static final int ENTRY = 48;
	public static final int FLOATING_POINT_LITERAL = 42;
	public static final int RBRACK = 3;
	public static final int PLUSASS = 34;
	public static final int MINUSASS = 35;
	public static final int DURING = 49;
	public static final int LSHIFT = 18;
	public static final int POINTER = 46;
	public static final int DIVASS = 32;
	public static final int GT = 21;
	public static final int XORASS = 38;
	public static final int RSHIFT = 19;
	public static final int NOTEQ = 25;
	public static final int INTEGER_LITERAL = 41;
}
