// COPYRIGHT NOTICE (NOT TO BE REMOVED):
//
// This file, or parts of it, or modified versions of it, may not be copied,
// reproduced or transmitted in any form, including reprinting, translation,
// photocopying or microfilming, or by any means, electronic, mechanical or
// otherwise, or stored in a retrieval system, or used for any purpose, without
// the prior written permission of all Owners unless it is explicitly marked as
// having Classification `Public'.
//   Classification: Restricted.
//
// Owners of this file give notice:
//   (c) Copyright 2010-2011 PES Software Engineering for Embedded Systems, TU Berlin
//
// Authors:
//		Sabine Glesner
//		Robert Reicherdt
//		Elke Salecker
//		Volker Seeker
//		Joachim Kuhnert
// 		Roman Busse
//
// All rights, including copyrights, reserved.
//
// This file contains or may contain restricted information and is UNPUBLISHED
// PROPRIETARY SOURCE CODE OF THE Owners.  The Copyright Notice(s) above do not
// evidence any actual or intended publication of such source code.  This file
// is additionally subject to the conditions listed in the RESTRICTIONS file
// and is with NO WARRANTY.
//
// END OF COPYRIGHT NOTICE

/* The following code was generated by JFlex 1.4.1 on 15.06.11 11:52 */

/*
 *  TEMPLATE for JFLEX-SCANNER 
 */

package de.tu_berlin.pes.memo.parser.stateflow.stateflowparser;

import java_cup.runtime.Symbol;
import de.tu_berlin.pes.memo.MeMoPlugin;

/**
 * This class is a scanner generated by <a href="http://www.jflex.de/">JFlex</a>
 * 1.4.1 on 15.06.11 11:52 from the specification file
 * <tt>D:/kuhnert/workspaceIntern/de.tu_berlin.pes.memo.parser.stateflow/grammar/StateflowTransitionScanner.jflex</tt>
 */
public class StateflowTransitionScanner implements java_cup.runtime.Scanner,
		StateflowTransitionScannerSymbol {

	/** This character denotes the end of file */
	public static final int YYEOF = -1;

	/** initial size of the lookahead buffer */
	private static final int ZZ_BUFFERSIZE = 16384;

	/** lexical states */
	public static final int STRING = 1;
	public static final int YYINITIAL = 0;
	public static final int COMMENT = 2;

	/**
	 * Translates characters to character classes
	 */
	private static final String ZZ_CMAP_PACKED = "\12\0\1\53\2\0\1\14\22\0\1\52\1\36\3\0\1\13\1\34"
			+ "\1\16\1\22\1\23\1\15\1\30\1\21\1\32\1\6\1\12\1\2"
			+ "\11\3\1\20\1\17\1\40\1\31\1\41\2\0\2\4\1\7\3\4"
			+ "\21\1\1\5\2\1\1\24\1\10\1\25\1\35\1\1\1\0\1\47"
			+ "\3\4\1\45\1\46\5\1\1\50\1\1\1\11\3\1\1\43\1\51"
			+ "\1\42\1\44\2\1\1\5\2\1\1\26\1\33\1\27\1\37\uff81\0";

	/**
	 * Translates characters to character classes
	 */
	private static final char[] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

	/**
	 * Translates DFA states to action switch labels.
	 */
	private static final int[] ZZ_ACTION = zzUnpackAction();

	private static final String ZZ_ACTION_PACKED_0 = "\3\0\1\1\1\2\2\3\1\4\1\1\1\5\1\1"
			+ "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15" + "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"
			+ "\1\26\1\27\1\30\1\31\1\32\2\2\1\33\1\34" + "\2\35\2\0\1\36\1\37\1\0\1\40\1\41\1\0"
			+ "\1\42\1\43\1\44\1\45\1\22\1\46\1\47\1\50" + "\1\51\1\52\1\53\1\54\1\55\1\56\1\57\1\60"
			+ "\1\61\1\62\1\63\1\64\1\65\2\2\1\66\1\67" + "\1\70\1\71\2\0\2\2\1\0\1\72\1\73\1\2"
			+ "\1\74";

	private static int[] zzUnpackAction() {
		int[] result = new int[82];
		int offset = 0;
		offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
		return result;
	}

	private static int zzUnpackAction(String packed, int offset, int[] result) {
		int i = 0; /* index in packed string */
		int j = offset; /* index in unpacked array */
		int l = packed.length();
		while (i < l) {
			int count = packed.charAt(i++);
			int value = packed.charAt(i++);
			do {
				result[j++] = value;
			} while (--count > 0);
		}
		return j;
	}

	/**
	 * Translates a state to a row index in the transition table
	 */
	private static final int[] ZZ_ROWMAP = zzUnpackRowMap();

	private static final String ZZ_ROWMAP_PACKED_0 = "\0\0\0\54\0\130\0\204\0\260\0\334\0\u0108\0\u0134"
			+ "\0\u0160\0\u018c\0\u01b8\0\u01e4\0\204\0\204\0\u0210\0\204"
			+ "\0\204\0\204\0\204\0\204\0\204\0\204\0\u023c\0\u0268"
			+ "\0\u0294\0\u02c0\0\u02ec\0\u0318\0\u0344\0\u0344\0\u0370\0\u039c"
			+ "\0\u03c8\0\u03f4\0\u0420\0\204\0\204\0\u044c\0\u0478\0\u04a4"
			+ "\0\204\0\u04d0\0\u04fc\0\204\0\204\0\u0528\0\204\0\204"
			+ "\0\204\0\204\0\204\0\204\0\204\0\204\0\204\0\204"
			+ "\0\204\0\204\0\204\0\204\0\204\0\204\0\204\0\204"
			+ "\0\204\0\204\0\204\0\u0554\0\u0580\0\204\0\u0478\0\204"
			+ "\0\204\0\u05ac\0\u05d8\0\u0604\0\u0630\0\u065c\0\204\0\260" + "\0\u0688\0\260";

	private static int[] zzUnpackRowMap() {
		int[] result = new int[82];
		int offset = 0;
		offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
		return result;
	}

	private static int zzUnpackRowMap(String packed, int offset, int[] result) {
		int i = 0; /* index in packed string */
		int j = offset; /* index in unpacked array */
		int l = packed.length();
		while (i < l) {
			int high = packed.charAt(i++) << 16;
			result[j++] = high | packed.charAt(i++);
		}
		return j;
	}

	/**
	 * The transition table of the DFA
	 */
	private static final int[] ZZ_TRANS = zzUnpackTrans();

	private static final String ZZ_TRANS_PACKED_0 = "\1\4\1\5\1\6\1\7\2\5\1\10\1\5\1\11"
			+ "\1\5\1\12\1\13\1\4\1\14\1\15\1\16\1\17" + "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"
			+ "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\1\37" + "\1\40\1\41\3\5\1\42\3\5\1\4\1\0\1\4"
			+ "\1\43\2\4\2\43\1\4\1\43\1\4\1\43\4\4" + "\1\44\23\4\10\43\1\45\1\0\10\45\1\46\3\45"
			+ "\1\4\36\45\56\0\5\5\1\0\1\5\1\0\1\5" + "\30\0\10\5\7\0\1\47\1\50\1\51\46\0\2\7"
			+ "\2\0\1\50\1\51\46\0\2\52\2\0\1\53\56\0" + "\1\54\54\0\1\55\2\0\1\56\13\0\1\57\22\0"
			+ "\13\60\1\61\1\0\36\60\32\0\1\62\53\0\1\63" + "\52\0\1\64\1\65\53\0\1\66\53\0\1\67\1\70"
			+ "\6\0\1\71\43\0\1\72\1\0\1\73\51\0\1\74" + "\2\0\1\75\50\0\1\76\53\0\1\77\53\0\1\100"
			+ "\6\0\1\101\1\77\43\0\1\102\7\0\1\103\13\0" + "\5\5\1\0\1\5\1\0\1\5\30\0\1\5\1\104"
			+ "\6\5\3\0\5\5\1\0\1\5\1\0\1\5\30\0" + "\5\5\1\105\2\5\3\0\5\43\1\0\1\43\1\0"
			+ "\1\43\30\0\10\43\13\0\1\106\44\0\3\107\2\0"
			+ "\1\107\35\0\3\107\6\0\2\52\52\0\2\52\3\0"
			+ "\1\110\52\0\1\111\45\0\15\112\1\113\36\112\1\0" + "\5\5\1\0\1\5\1\0\1\5\30\0\2\5\1\114"
			+ "\5\5\3\0\5\5\1\0\1\5\1\0\1\5\30\0" + "\6\5\1\115\1\5\2\0\15\112\1\116\36\112\12\0"
			+ "\1\117\2\0\1\113\37\0\5\5\1\0\1\5\1\0" + "\1\5\30\0\3\5\1\120\4\5\3\0\5\5\1\0"
			+ "\1\5\1\0\1\5\30\0\7\5\1\121\2\0\12\112" + "\1\117\2\112\1\116\36\112\1\0\5\5\1\0\1\5"
			+ "\1\0\1\5\30\0\3\5\1\122\4\5\2\0";

	private static int[] zzUnpackTrans() {
		int[] result = new int[1716];
		int offset = 0;
		offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
		return result;
	}

	private static int zzUnpackTrans(String packed, int offset, int[] result) {
		int i = 0; /* index in packed string */
		int j = offset; /* index in unpacked array */
		int l = packed.length();
		while (i < l) {
			int count = packed.charAt(i++);
			int value = packed.charAt(i++);
			value--;
			do {
				result[j++] = value;
			} while (--count > 0);
		}
		return j;
	}

	/* error codes */
	private static final int ZZ_UNKNOWN_ERROR = 0;
	private static final int ZZ_NO_MATCH = 1;
	private static final int ZZ_PUSHBACK_2BIG = 2;

	/* error messages for the codes above */
	private static final String ZZ_ERROR_MSG[] = { "Unkown internal scanner error",
			"Error: could not match input", "Error: pushback value was too large" };

	/**
	 * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
	 */
	private static final int[] ZZ_ATTRIBUTE = zzUnpackAttribute();

	private static final String ZZ_ATTRIBUTE_PACKED_0 = "\3\0\1\11\10\1\2\11\1\1\7\11\15\1\2\11"
			+ "\1\1\2\0\1\11\1\1\1\0\2\11\1\0\25\11" + "\2\1\1\11\1\1\2\11\2\0\2\1\1\0\1\11" + "\3\1";

	private static int[] zzUnpackAttribute() {
		int[] result = new int[82];
		int offset = 0;
		offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
		return result;
	}

	private static int zzUnpackAttribute(String packed, int offset, int[] result) {
		int i = 0; /* index in packed string */
		int j = offset; /* index in unpacked array */
		int l = packed.length();
		while (i < l) {
			int count = packed.charAt(i++);
			int value = packed.charAt(i++);
			do {
				result[j++] = value;
			} while (--count > 0);
		}
		return j;
	}

	/** the input device */
	private java.io.Reader zzReader;

	/** the current state of the DFA */
	private int zzState;

	/** the current lexical state */
	private int zzLexicalState = YYINITIAL;

	/**
	 * this buffer contains the current text to be matched and is the source of
	 * the yytext() string
	 */
	private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

	/** the textposition at the last accepting state */
	private int zzMarkedPos;

	/** the textposition at the last state to be included in yytext */
	private int zzPushbackPos;

	/** the current text position in the buffer */
	private int zzCurrentPos;

	/** startRead marks the beginning of the yytext() string in the buffer */
	private int zzStartRead;

	/**
	 * endRead marks the last character in the buffer, that has been read from
	 * input
	 */
	private int zzEndRead;

	/** number of newlines encountered up to the start of the matched text */
	private int yyline;

	/** the number of characters up to the start of the matched text */
	private int yychar;

	/**
	 * the number of characters from the last newline up to the start of the
	 * matched text
	 */
	private int yycolumn;

	/**
	 * zzAtBOL == true <=> the scanner is currently at the beginning of a line
	 */
	private boolean zzAtBOL = true;

	/** zzAtEOF == true <=> the scanner is at the EOF */
	private boolean zzAtEOF;

	/** denotes if the user-EOF-code has already been executed */
	private boolean zzEOFDone;

	/* user code: */
	boolean debug = false;
	private StringBuffer string = new StringBuffer();

	public void setDebug(boolean debug) {
		this.debug = debug;
	}

	private Symbol symbol(int sym) {
		return new Symbol(sym, yyline + 1, yycolumn + 1);
	}

	private Symbol symbol(int sym, Object val) {
		return new Symbol(sym, yyline + 1, yycolumn + 1, val);
	}

	private void out(String message) {
		if (debug) {
			MeMoPlugin.out.println("LEX: " + message);
		}
	}

	/**
	 * Creates a new scanner There is also a java.io.InputStream version of this
	 * constructor.
	 *
	 * @param in
	 *           the java.io.Reader to read input from.
	 */
	public StateflowTransitionScanner(java.io.Reader in) {
		this.zzReader = in;
	}

	/**
	 * Creates a new scanner. There is also java.io.Reader version of this
	 * constructor.
	 *
	 * @param in
	 *           the java.io.Inputstream to read input from.
	 */
	public StateflowTransitionScanner(java.io.InputStream in) {
		this(new java.io.InputStreamReader(in));
	}

	/**
	 * Unpacks the compressed character translation table.
	 *
	 * @param packed
	 *           the packed character translation table
	 * @return the unpacked character translation table
	 */
	private static char[] zzUnpackCMap(String packed) {
		char[] map = new char[0x10000];
		int i = 0; /* index in packed string */
		int j = 0; /* index in unpacked array */
		while (i < 120) {
			int count = packed.charAt(i++);
			char value = packed.charAt(i++);
			do {
				map[j++] = value;
			} while (--count > 0);
		}
		return map;
	}

	/**
	 * Refills the input buffer.
	 *
	 * @return <code>false</code>, iff there was new input.
	 * 
	 * @exception java.io.IOException
	 *               if any I/O-Error occurs
	 */
	private boolean zzRefill() throws java.io.IOException {

		/* first: make room (if you can) */
		if (zzStartRead > 0) {
			System.arraycopy(zzBuffer, zzStartRead, zzBuffer, 0, zzEndRead - zzStartRead);

			/* translate stored positions */
			zzEndRead -= zzStartRead;
			zzCurrentPos -= zzStartRead;
			zzMarkedPos -= zzStartRead;
			zzPushbackPos -= zzStartRead;
			zzStartRead = 0;
		}

		/* is the buffer big enough? */
		if (zzCurrentPos >= zzBuffer.length) {
			/* if not: blow it up */
			char newBuffer[] = new char[zzCurrentPos * 2];
			System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
			zzBuffer = newBuffer;
		}

		/* finally: fill the buffer with new input */
		int numRead = zzReader.read(zzBuffer, zzEndRead, zzBuffer.length - zzEndRead);

		if (numRead < 0) {
			return true;
		} else {
			zzEndRead += numRead;
			return false;
		}
	}

	/**
	 * Closes the input stream.
	 */
	public final void yyclose() throws java.io.IOException {
		zzAtEOF = true; /* indicate end of file */
		zzEndRead = zzStartRead; /* invalidate buffer */

		if (zzReader != null) {
			zzReader.close();
		}
	}

	/**
	 * Resets the scanner to read from a new input stream. Does not close the old
	 * reader.
	 *
	 * All internal variables are reset, the old input stream <b>cannot</b> be
	 * reused (internal buffer is discarded and lost). Lexical state is set to
	 * <tt>ZZ_INITIAL</tt>.
	 *
	 * @param reader
	 *           the new input stream
	 */
	public final void yyreset(java.io.Reader reader) {
		zzReader = reader;
		zzAtBOL = true;
		zzAtEOF = false;
		zzEndRead = zzStartRead = 0;
		zzCurrentPos = zzMarkedPos = zzPushbackPos = 0;
		yyline = yychar = yycolumn = 0;
		zzLexicalState = YYINITIAL;
	}

	/**
	 * Returns the current lexical state.
	 */
	public final int yystate() {
		return zzLexicalState;
	}

	/**
	 * Enters a new lexical state
	 *
	 * @param newState
	 *           the new lexical state
	 */
	public final void yybegin(int newState) {
		zzLexicalState = newState;
	}

	/**
	 * Returns the text matched by the current regular expression.
	 */
	public final String yytext() {
		return new String(zzBuffer, zzStartRead, zzMarkedPos - zzStartRead);
	}

	/**
	 * Returns the character at position <tt>pos</tt> from the matched text.
	 * 
	 * It is equivalent to yytext().charAt(pos), but faster
	 *
	 * @param pos
	 *           the position of the character to fetch. A value from 0 to
	 *           yylength()-1.
	 *
	 * @return the character at position pos
	 */
	public final char yycharat(int pos) {
		return zzBuffer[zzStartRead + pos];
	}

	/**
	 * Returns the length of the matched text region.
	 */
	public final int yylength() {
		return zzMarkedPos - zzStartRead;
	}

	/**
	 * Reports an error that occured while scanning.
	 *
	 * In a wellformed scanner (no or only correct usage of yypushback(int) and a
	 * match-all fallback rule) this method will only be called with things that
	 * "Can't Possibly Happen". If this method is called, something is seriously
	 * wrong (e.g. a JFlex bug producing a faulty scanner etc.).
	 *
	 * Usual syntax/scanner level error handling should be done in error fallback
	 * rules.
	 *
	 * @param errorCode
	 *           the code of the errormessage to display
	 */
	private void zzScanError(int errorCode) {
		String message;
		try {
			message = ZZ_ERROR_MSG[errorCode];
		} catch (ArrayIndexOutOfBoundsException e) {
			message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
		}

		throw new Error(message);
	}

	/**
	 * Pushes the specified amount of characters back into the input stream.
	 *
	 * They will be read again by then next call of the scanning method
	 *
	 * @param number
	 *           the number of characters to be read again. This number must not
	 *           be greater than yylength()!
	 */
	public void yypushback(int number) {
		if (number > yylength()) {
			zzScanError(ZZ_PUSHBACK_2BIG);
		}

		zzMarkedPos -= number;
	}

	/**
	 * Contains user EOF-code, which will be executed exactly once, when the end
	 * of file is reached
	 */
	private void zzDoEOF() throws java.io.IOException {
		if (!zzEOFDone) {
			zzEOFDone = true;
			yyclose();
		}
	}

	/**
	 * Resumes scanning until the next regular expression is matched, the end of
	 * input is encountered or an I/O-Error occurs.
	 *
	 * @return the next token
	 * @exception java.io.IOException
	 *               if any I/O-Error occurs
	 */
	@Override
	public java_cup.runtime.Symbol next_token() throws java.io.IOException {
		int zzInput;
		int zzAction;

		// cached fields:
		int zzCurrentPosL;
		int zzMarkedPosL;
		int zzEndReadL = zzEndRead;
		char[] zzBufferL = zzBuffer;
		char[] zzCMapL = ZZ_CMAP;

		int[] zzTransL = ZZ_TRANS;
		int[] zzRowMapL = ZZ_ROWMAP;
		int[] zzAttrL = ZZ_ATTRIBUTE;

		while (true) {
			zzMarkedPosL = zzMarkedPos;

			boolean zzR = false;
			for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL; zzCurrentPosL++) {
				switch (zzBufferL[zzCurrentPosL]) {
					case '\u000B':
					case '\u000C':
					case '\u0085':
					case '\u2028':
					case '\u2029':
						yyline++;
						yycolumn = 0;
						zzR = false;
						break;
					case '\r':
						yyline++;
						yycolumn = 0;
						zzR = true;
						break;
					case '\n':
						if (zzR) {
							zzR = false;
						} else {
							yyline++;
							yycolumn = 0;
						}
						break;
					default:
						zzR = false;
						yycolumn++;
				}
			}

			if (zzR) {
				// peek one character ahead if it is \n (if we have counted one line
				// too much)
				boolean zzPeek;
				if (zzMarkedPosL < zzEndReadL) {
					zzPeek = zzBufferL[zzMarkedPosL] == '\n';
				} else if (zzAtEOF) {
					zzPeek = false;
				} else {
					boolean eof = zzRefill();
					zzEndReadL = zzEndRead;
					zzMarkedPosL = zzMarkedPos;
					zzBufferL = zzBuffer;
					if (eof) {
						zzPeek = false;
					} else {
						zzPeek = zzBufferL[zzMarkedPosL] == '\n';
					}
				}
				if (zzPeek) {
					yyline--;
				}
			}
			zzAction = -1;

			zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

			zzState = zzLexicalState;

			zzForAction: {
				while (true) {

					if (zzCurrentPosL < zzEndReadL) {
						zzInput = zzBufferL[zzCurrentPosL++];
					} else if (zzAtEOF) {
						zzInput = YYEOF;
						break zzForAction;
					} else {
						// store back cached positions
						zzCurrentPos = zzCurrentPosL;
						zzMarkedPos = zzMarkedPosL;
						boolean eof = zzRefill();
						// get translated positions and possibly new buffer
						zzCurrentPosL = zzCurrentPos;
						zzMarkedPosL = zzMarkedPos;
						zzBufferL = zzBuffer;
						zzEndReadL = zzEndRead;
						if (eof) {
							zzInput = YYEOF;
							break zzForAction;
						} else {
							zzInput = zzBufferL[zzCurrentPosL++];
						}
					}
					int zzNext = zzTransL[zzRowMapL[zzState] + zzCMapL[zzInput]];
					if (zzNext == -1) {
						break zzForAction;
					}
					zzState = zzNext;

					int zzAttributes = zzAttrL[zzState];
					if ((zzAttributes & 1) == 1) {
						zzAction = zzState;
						zzMarkedPosL = zzCurrentPosL;
						if ((zzAttributes & 8) == 8) {
							break zzForAction;
						}
					}

				}
			}

			// store back cached position
			zzMarkedPos = zzMarkedPosL;

			switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
				case 31: {
					out("FLOAT_NUMBER: " + yytext());
					return symbol(StateflowTransitionScannerSymbol.FLOATING_POINT_LITERAL, new Float(
							yytext()));
				}
				case 61:
					break;
				case 27: {
					out("APPENDING STRING: " + yytext());
					string.append(yytext());
				}
				case 62:
					break;
				case 59: {
					out("True literal");
					return symbol(StateflowTransitionScannerSymbol.BOOLEAN_LITERAL, new Boolean(true));
				}
				case 63:
					break;
				case 49: {
					out("NotEquals");
					return symbol(StateflowTransitionScannerSymbol.NOTEQ);
				}
				case 64:
					break;
				case 47: {
					out("LogicalAnd");
					return symbol(StateflowTransitionScannerSymbol.ANDAND);
				}
				case 65:
					break;
				case 36: {
					out("Modulo");
					return symbol(StateflowTransitionScannerSymbol.MOD);
				}
				case 66:
					break;
				case 5: {
					out("Slash");
					return symbol(StateflowTransitionScannerSymbol.DIV);
				}
				case 67:
					break;
				case 33: {
					out("C-Comment.Switching to Comment-MODE: " + yytext());
					string.setLength(0);
					yybegin(COMMENT);
				}
				case 68:
					break;
				case 58: {
					out("C-BlockComment: " + yytext());
				}
				case 69:
					break;
				case 18: {
					out("Assignment");
					return symbol(StateflowTransitionScannerSymbol.ASS);
				}
				case 70:
					break;
				case 57: {
					out("IGNORED TripleDot");
				}
				case 71:
					break;
				case 8: {
					out("SemiColon");
					return symbol(StateflowTransitionScannerSymbol.SEMICOLON);
				}
				case 72:
					break;
				case 60: {
					out("False literal");
					return symbol(StateflowTransitionScannerSymbol.BOOLEAN_LITERAL, new Boolean(false));
				}
				case 73:
					break;
				case 16: {
					out("RightCurl");
					return symbol(StateflowTransitionScannerSymbol.RBRACE);
				}
				case 74:
					break;
				case 25: {
					out("SmallerThan");
					return symbol(StateflowTransitionScannerSymbol.LT);
				}
				case 75:
					break;
				case 34: {
					out("DivAssignment");
					return symbol(StateflowTransitionScannerSymbol.DIVASS);
				}
				case 76:
					break;
				case 41: {
					out("SubAssignment");
					return symbol(StateflowTransitionScannerSymbol.MINUSASS);
				}
				case 77:
					break;
				case 35: {
					out("MATLAB-Comment.Switching to Comment-MODE: " + yytext());
					string.setLength(0);
					yybegin(COMMENT);
				}
				case 78:
					break;
				case 14: {
					out("RightBracket");
					return symbol(StateflowTransitionScannerSymbol.RBRACK);
				}
				case 79:
					break;
				case 19: {
					out("Minus");
					return symbol(StateflowTransitionScannerSymbol.MINUS);
				}
				case 80:
					break;
				case 53: {
					out("RightShift");
					return symbol(StateflowTransitionScannerSymbol.RSHIFT);
				}
				case 81:
					break;
				case 54: {
					yybegin(YYINITIAL);
					out("FOUND Comment: " + string.toString());
				}
				case 82:
					break;
				case 7: {
					out("FUNCTION-ARGUMENT-STRING WILL FOLLOW");
					string.setLength(0);
					yybegin(STRING);
				}
				case 83:
					break;
				case 55: {
					out("HEXADEZIMAL_NUMBER: " + yytext());
					string.setLength(0);
					string.append(yytext());
					string.delete(0, 2);
					return symbol(StateflowTransitionScannerSymbol.INTEGER_LITERAL,
							new Long(Long.parseLong(string.toString(), 16)));
				}
				case 84:
					break;
				case 12: {
					out("RightParenthesis");
					return symbol(StateflowTransitionScannerSymbol.RPAREN);
				}
				case 85:
					break;
				case 51: {
					out("LeftShift");
					return symbol(StateflowTransitionScannerSymbol.LSHIFT);
				}
				case 86:
					break;
				case 46: {
					out("ANDAssignment");
					return symbol(StateflowTransitionScannerSymbol.ANDASS);
				}
				case 87:
					break;
				case 6: {
					out("Multiplication");
					return symbol(StateflowTransitionScannerSymbol.MULT);
				}
				case 88:
					break;
				case 30: {
					out("CONST_INTEGER: " + yytext());
					string.setLength(0);
					string.append(yytext());
					string.deleteCharAt(string.length() - 1);
					return symbol(StateflowTransitionScannerSymbol.INTEGER_LITERAL,
							new Long(string.toString()));
				}
				case 89:
					break;
				case 20: {
					out("InclusiveOr");
					return symbol(StateflowTransitionScannerSymbol.OR);
				}
				case 90:
					break;
				case 39: {
					out("AddAssignment");
					return symbol(StateflowTransitionScannerSymbol.PLUSASS);
				}
				case 91:
					break;
				case 11: {
					out("LeftParenthesis");
					return symbol(StateflowTransitionScannerSymbol.LPAREN);
				}
				case 92:
					break;
				case 24: {
					out("TildeNot");
					return symbol(StateflowTransitionScannerSymbol.NOT);
				}
				case 93:
					break;
				case 52: {
					out("GreaterOrEquals");
					return symbol(StateflowTransitionScannerSymbol.GTEQ);
				}
				case 94:
					break;
				case 17: {
					out("Plus");
					return symbol(StateflowTransitionScannerSymbol.PLUS);
				}
				case 95:
					break;
				case 10: {
					out("Comma");
					return symbol(StateflowTransitionScannerSymbol.COMMA);
				}
				case 96:
					break;
				case 48: {
					out("XORAssignment");
					return symbol(StateflowTransitionScannerSymbol.XORASS);
				}
				case 97:
					break;
				case 37: {
					out("MultAssignment");
					return symbol(StateflowTransitionScannerSymbol.MULTASS);
				}
				case 98:
					break;
				case 32: {
					out("IGNORED MATLABNewLine Symbol");
				}
				case 99:
					break;
				case 21: {
					out("InclusiveAnd");
					return symbol(StateflowTransitionScannerSymbol.AND);
				}
				case 100:
					break;
				case 1: { // out("Illegal character <"+ yytext()+">");
				}
				case 101:
					break;
				case 45: {
					out("LogicalOR");
					return symbol(StateflowTransitionScannerSymbol.OROR);
				}
				case 102:
					break;
				case 38: {
					out("Increment");
					return symbol(StateflowTransitionScannerSymbol.PLUSPLUS);
				}
				case 103:
					break;
				case 44: {
					out("ORAssignment");
					return symbol(StateflowTransitionScannerSymbol.ORASS);
				}
				case 104:
					break;
				case 56: {
					out("CONST_FLOAT: " + yytext());
					string.setLength(0);
					string.append(yytext());
					string.deleteCharAt(string.length() - 1);
					return symbol(StateflowTransitionScannerSymbol.FLOATING_POINT_LITERAL, new Float(
							string.toString()));
				}
				case 105:
					break;
				case 22: {
					out("ExclusiveOR");
					return symbol(StateflowTransitionScannerSymbol.XOR);
				}
				case 106:
					break;
				case 40: {
					out("Equals");
					return symbol(StateflowTransitionScannerSymbol.EQEQ);
				}
				case 107:
					break;
				case 4: {
					out("Dot");
					return symbol(StateflowTransitionScannerSymbol.DOT);
				}
				case 108:
					break;
				case 42: {
					out("Decrement");
					return symbol(StateflowTransitionScannerSymbol.MINUSMINUS);
				}
				case 109:
					break;
				case 29: {
					string.append(yytext());
				}
				case 110:
					break;
				case 26: {
					out("GreaterThan");
					return symbol(StateflowTransitionScannerSymbol.GT);
				}
				case 111:
					break;
				case 28: {
					yybegin(YYINITIAL);
					out("FOUND STRING: " + "'" + string.toString() + "'");
					return symbol(StateflowTransitionScannerSymbol.STRING_LITERAL, string.toString());
				}
				case 112:
					break;
				case 43: {
					out("StructArrow ->");
					return symbol(StateflowTransitionScannerSymbol.ARROW);
				}
				case 113:
					break;
				case 2: {
					out("IDENT: " + yytext());
					return symbol(StateflowTransitionScannerSymbol.ID, yytext());
				}
				case 114:
					break;
				case 13: {
					out("LeftBracket");
					return symbol(StateflowTransitionScannerSymbol.LBRACK);
				}
				case 115:
					break;
				case 9: {
					out("Colon");
					return symbol(StateflowTransitionScannerSymbol.COLON);
				}
				case 116:
					break;
				case 23: {
					out("NOT");
					return symbol(StateflowTransitionScannerSymbol.NOT);
				}
				case 117:
					break;
				case 15: {
					out("LeftCurl");
					return symbol(StateflowTransitionScannerSymbol.LBRACE);
				}
				case 118:
					break;
				case 50: {
					out("SmallerOrEquals");
					return symbol(StateflowTransitionScannerSymbol.LTEQ);
				}
				case 119:
					break;
				case 3: {
					out("INT: " + yytext());
					return symbol(StateflowTransitionScannerSymbol.INTEGER_LITERAL, new Long(yytext()));
				}
				case 120:
					break;
				default:
					if ((zzInput == YYEOF) && (zzStartRead == zzCurrentPos)) {
						zzAtEOF = true;
						zzDoEOF();
						{
							return new Symbol(StateflowTransitionScannerSymbol.EOF);
						}
					} else {
						zzScanError(ZZ_NO_MATCH);
					}
			}
		}
	}

}
